baseURL = "http://mike2ykme.github.io/"
languageCode = "en-us"
title = "Mike's Blog"
theme = "blogolio"
pygmentsUseClasses = true
    [params]
    dev = false
    author = "Micheal Arsenault"

    gh_url = "https://api.github.com/users"
    gh_user = "mike2ykme"
    tagsLimit = 50
    
    [permalinks]
    posts="posts/:year/:month/:slug"
    year = "/posts/:slug"
    month = "/posts/:slug"

    [taxonomies]
    year = "year"
    month = "month"
    tag = "tags"
    series = "series"
    category = "categories"